{{- if .Values.global.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oryo.fullname" . }}-secrets
  labels:
    {{- include "oryo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.global.secrets }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
